cnt_agents: &cnt_agents 3
max_turn: &max_turn 1
max_criticizing_rounds: 0

prompts:
  role_assigner_prepend_prompt: &role_assigner_prepend_prompt |-

  role_assigner_append_prompt: &role_assigner_append_prompt |-
    Generate a list of ${cnt_critic_agents} names. Here is an example of your response:
    EXAMPLE:
    1. Alice
    2. Bob
    3. Charli
    ...
# You are the leader of a group, now you are facing a problem:
# ```
# ${task_description}
# ```

# You can recruit ${cnt_critic_agents} people to solve the logic problem. What people will you recruit?

# Here are some suggestion:
# ${advice}

# ## Response Format Guidance
# You should respond with a list of expert names. For example:
# 1. Alice
# 2. Bob
# 3. Charlie
# ...

# Only respond with the names. Do not include your reason.

  solver_prepend_prompt: &solver_prepend_prompt |-


  # Messages from the solver and critics will be filled here in the code.
  
  solver_append_prompt: &solver_append_prompt |-
    ${task_description}

    At the end of your response, you must give your answer in the form of "the answer is: {number}", where {number} is the answer number. Now solve the problem step-by-step.

# Using these information, can you provide the correct solution to the math problem? Explain your reasoning and solve the problem step by step. Your final answer should be a single integer, which is the number of choice, in the form \boxed{answer}, at the end of your response.

  critic_prepend_prompt: &critic_prepend_prompt |-
    You are ${agent_name}. Together with ${all_roles}, you are providing accurate answer to the user. Each of you will be provided parts of the contexts and a shared question. 

    EXAMPLE 1
    ---
    # Context
    ...
    A few miles from the town of Southampton there is an old mansion-house, which has been for centuries known as Madeline Hall, in the possession of the de Versely family.  It is a handsome building, surrounded by a finely timbered park of some extent, and, what is more important, by about 12,000 acres of land, which also appertain to it.  At the period in which I commence this history, there resided in this mansion an elderly spinster of rank, named the Honourable Miss Delmar, sister of the late Lord de Versely and aunt to the present earl, and an Honourable Captain Delmar, who was the second son of the deceased nobleman.  This property belonged to the Honourable Miss Delmar, and was at her entire disposal upon her decease. 
    ...

    # Question
    Who is Miss Delmer?
    ---
    The answer is "the elderly spinster aunt of the Earl de Verseley and Captain Delmar" or "She's Captail Delmar's aunt.".

    EXAMPLE 2
    ---
    # Context
    A teenage boy stands in front of an in-mall theatre across from Swenson's. He wears a stiff over-sized tuxedo suit. He is Mark "The Rat" Ratner, a ticket taker on the job.

    Mike Damone, a transplanted Easterner, bops over from the record store, eyeing every girl he passes. He stops at the movie theatre.
    ...(other unrelevant contexts)

    # Question
    Who is Miss Delmer?
    ---
    You don't have relevant context on the question, so you need to communication with others.

    Now the user gives you some contexts and the question:
    ---
    # Context
    ${knowledge}

    # Question
    ${task_description}
    ---

    Given that each individual, including yourself, possesses unique contexts, your specific context is unknown to others unless explicitly communicated. However, answers may need to be deduced from contexts that are visible to various individuals. Therefore, it is important to engage in communication with others.

    Once you have formulated the final answer, enclose it within "<A>xxx</A>", where "xxx" represents the answer phrase selected from the given choices. The conversation concludes when all participants have presented the same answer in this format. If you have different opinion, explain it to your teammates.

    You are ${agent_name}, collaborating with ${all_roles}. Now, start communicating with others. Remember, clarity and brevity are key. Send concise and clear message using as few words as possible. 
  critic_append_prompt: &critic_append_prompt |-


  evaluator_prepend_prompt: &evaluator_prepend_prompt |-
    Problem:
    ```
    ${task_description}
    ```

    Solution: 
    ```
    ${solution}
    ```

    You are a logic problem lover. Above is a logic problem and a solution. Check whether the solution and the deduction is correct. If the deduction is wrong, you should explain why it is wrong, but do not give your solution. When it is correct, output a correctness of 1 and why it is correct.
    
  evaluator_append_prompt: &evaluator_append_prompt |-
    You should respond in the following format:
    Correctness: (0 or 1, 0 is wrong, and 1 is correct)
    Response: (explain in details why it is wrong or correct. do not provide your solution)

    


name: pipeline


environment:
  env_type: task-basic
  max_turn: *max_turn
  rule:
    role_assigner:
      type: role_description
      cnt_agents: *cnt_agents
    decision_maker:
      type: debate
      max_turns: 8
    executor:
      type: none
    evaluator:
      type: dummy-true

agents:
  - #role_assigner_agent:
    agent_type: role_assigner
    name: role assigner
    max_retry: 1000
    prepend_prompt_template: *role_assigner_prepend_prompt
    append_prompt_template: *role_assigner_append_prompt
    memory:
      memory_type: chat_history
    llm:
      llm_type: gpt-4
      model: gpt-4-1106
      temperature: 0
      max_tokens: 512
    output_parser:
      type: role_assigner
      
  - #solver_agent:
    agent_type: solver
    name: Planner
    max_retry: 1000
    prepend_prompt_template: *solver_prepend_prompt
    append_prompt_template: *solver_append_prompt
    memory:
      memory_type: chat_history
    llm:
      llm_type: gpt-3.5-turbo
      model: gpt-3.5-turbo-0301
      max_tokens: 1024
      temperature: 0
    output_parser:
      type: mgsm

  - #critic_agents:
    agent_type: critic
    name: Critic 1
    max_retry: 1000
    max_history: 20
    role_description: |-
      Waiting to be assigned.
    prepend_prompt_template: *critic_prepend_prompt
    append_prompt_template: *critic_append_prompt
    memory:
      memory_type: chat_history
      add_sender_prefix: false
      add_sender_in_message: true
    flatten: false
    llm:
      llm_type: gpt-4
      model: gpt-4-1106
      temperature: 0
    output_parser:
      type: qa-critic

  - #executor_agent:
    agent_type: executor
    name: Executor
    max_retry: 1000
    memory:
      memory_type: chat_history
    llm:
      llm_type: gpt-4
      model: gpt-4-1106
      temperature: 0
      max_tokens: 1024
    output_parser:
      type: mgsm

  - #evaluator_agent:
    agent_type: evaluator
    name: Evaluator
    max_retry: 1000
    role_description: |-
      Evaluator
    prepend_prompt_template: *evaluator_prepend_prompt
    append_prompt_template: *evaluator_append_prompt
    memory:
      memory_type: chat_history
    llm:
      llm_type: gpt-4
      model: gpt-4-1106
      temperature: 0.3
      max_tokens: 1024
    output_parser:
      type: mgsm-evaluator
      dimensions:
        - Correctness


tools:

